name: lcls_cu_inj_nn_ex_env
channels:
  - conda-forge
dependencies:
  - Python=3.9
  - lume-model=0.13
  - tensorflow
  - numpy
  - prefect[kubernetes]
  - pip
  - pip:
    - git+https://github.com/jacquelinegarrahan/lcls-cu-inj-nn-ex.git